version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    hostname: plex
    network_mode: host
    
    environment:
      - TZ="America/Los_Angeles"
      - PLEX_CLAIM="claim-8HqhoneHXHPemY7rDPAy"
      - PLEX_UID="9000"
      - PLEX_GID="9000"
      - ALLOWED_NETWORKS="10.0.0.0/8,192.168.0.0/16,127.0.0.0/8"
      - LAN Networks="10.0.0.0/8,192.168.0.0/16,127.0.0.0/8"

    volumes:
      - /docker/plex/config:/config
      - /docker/plex/tmp:/transcode
      - /docker/plex/data:/data
